# Generated by Django 4.2.3 on 2023-08-08 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('year', models.CharField(blank=True, default='', max_length=255)),
                ('millage', models.CharField(blank=True, default='', max_length=255)),
                ('fuel_type', models.CharField(blank=True, default='', max_length=255)),
                ('transmission', models.CharField(blank=True, default='', max_length=255)),
                ('horsepower', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(default='', max_length=255)),
                ('more_information', models.CharField(blank=True, default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='', max_length=255)),
                ('date', models.DateField(auto_now_add=True, verbose_name='')),
                ('ads', models.ForeignKey(default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='Ads.ads')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=255)),
                ('car', models.ForeignKey(default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Ads.ads')),
            ],
        ),
        migrations.AddField(
            model_name='ads',
            name='main_image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Ads.mainimage'),
        ),
    ]
