# Generated by Django 4.2.3 on 2023-08-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='amount',
            new_name='price',
        ),
    ]
