# Generated by Django 4.2.3 on 2023-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
