# Generated by Django 4.2.3 on 2023-08-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_ads_url'),
        ('Ads', '0002_rename_amount_price_price'),
    ]

    operations = [
    ]
