# Generated by Django 4.2.3 on 2023-08-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0004_rename_car_image_ad_rename_ads_price_ad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='ads',
            name='color',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='fuel_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='horsepower',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='millage',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='more_information',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='transmission',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='year',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
