# Generated by Django 4.2.3 on 2023-08-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0005_alter_price_options_alter_ads_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-date']},
        ),
    ]
