# Generated by Django 4.2.3 on 2023-08-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0006_alter_price_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['date']},
        ),
    ]
